@baseUrl = http://localhost:3000
@userId = 6a43af60a011a4b3a30f06b6

### TEST API
GET {{baseUrl}}

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe4@example.com",
  "email": "john.doe5@example.com",
  "password": "test123"
}

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{userId}}

### UPDATE USER BY ID
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated"
}

### DELETE USER BY ID
DELETE {{baseUrl}}/users/{{userId}}

###REGISTER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jane@example.com",
  "password": "test123"
}