@baseUrl = http://localhost:3000
@userId = 6a7082510a8a38c08131920f
@tripId =6a7083da0a8a38c081319211
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTcwODI1MTBhOGEzOGMwODEzMTkyMGYiLCJpYXQiOjE3ODU5Mzc0NDQsImV4cCI6MTc4NjAyMzg0NH0.L69v9raZduImf5wtJ2h6YL6Zk8YQxL9OUaiStkxNxbY
@tripToken=

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe4@example.com",
  "password": "test123"
}

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{userId}}

### UPDATE USER BY ID
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated"
}

### DELETE USER BY ID
DELETE {{baseUrl}}/users/{{userId}}

###REGISTER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jane789@example.com",
  "password": "test123"
}

###LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "jane789@example.com",
  "password": "test123"
}
###CREATE TRIP
POST {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user": "{{userId}}",
  "title": "Trip to the moon",
  "startDate": "2025-12-15",
  "endDate": "2025-12-16",
  "budget": {
    "total": 1000
  },
  "destinations": ["Moon", "Mars", "Jupiter"]
}
### GET ALL TRIPS
GET {{baseUrl}}/trips
Authorization: Bearer {{token}}

### GET TRIP BY ID
GET {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}

### UPDATE TRIP BY ID
PATCH {{baseUrl}}/trips/{{tripId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trip to the moon and back",
  "budget": {
    "total": 1500
  }
}

### DELETE TRIP BY ID
DELETE {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}


### CREATE BAGGAGE
POST {{baseUrl}}/{{tripId}}/baggages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Jacket"
}

### SEND TRIP INVITATION
POST {{baseUrl}}/trips/{{tripId}}/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "collaboratorEmails": [
"apsankatuwal5@gmail.com"
  ]
}

### ACCEPT TRIP INVITATION
